# Generated by Django 6.0.3 on 2026-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
