# Generated by Django 6.0.3 on 2026-06-03 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_membership_idx_membership_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('project_archived', 'Project Archived'), ('member_invited', 'Member Invited'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('org_updated', 'Organization Updated')], max_length=50)),
                ('entity_type', models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('membership', 'Membership'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='idx_activity_org'), models.Index(fields=['user'], name='idx_activity_user'), models.Index(fields=['action'], name='idx_activity_action'), models.Index(fields=['entity_type', 'entity_id'], name='idx_activity_entity')],
            },
        ),
    ]
