# Generated by Django 6.0.3 on 2026-06-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('project_archived', 'Project Archived'), ('member_invited', 'Member Invited'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('org_updated', 'Organization Updated'), ('ai_call', 'AI Call')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('task', 'Task'), ('project', 'Project'), ('membership', 'Membership'), ('organization', 'Organization'), ('ai', 'AI')], max_length=20, null=True),
        ),
    ]
