# Generated by Django 6.0.3 on 2026-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(choices=[('pending', 'Pending'), ('org_created', 'Organization Created'), ('team_invited', 'Team Invited'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
