# Generated by Django 6.0.3 on 2026-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_idx_membership_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='purpose',
            field=models.CharField(blank=True, choices=[('product_engineering', 'Product & Engineering'), ('agency_clients', 'Agency & Clients'), ('marketing_content', 'Marketing & Content'), ('operations_other', 'Operations & Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, choices=[('just_me', 'Just Me'), ('2_10', '2-10'), ('11_50', '11-50'), ('51_200', '51-200'), ('200_plus', '200+')], max_length=20),
        ),
    ]
