# Generated by Django 6.0.3 on 2026-07-16 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_membership_status_organization_purpose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink')], default='purple', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to='organizations.organization')),
            ],
            options={
                'db_table': 'pending_invites',
                'indexes': [models.Index(fields=['email'], name='idx_pending_invite_email'), models.Index(fields=['token'], name='idx_pending_invite_token')],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
