# Generated by Django 6.0.3 on 2026-06-02 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_updated_at_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization'], name='idx_project_org'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_project_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='idx_project_org_status'),
        ),
    ]
