# Generated by Django 6.0.3 on 2026-06-29 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_idx_project_org_project_idx_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.CharField(choices=[('product_sprint', 'Product / Sprint'), ('marketing_campaign', 'Marketing Campaign'), ('design_agency', 'Design / Agency'), ('blank', 'Blank Project')], default='blank', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.project')),
            ],
            options={
                'db_table': 'project_columns',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['project', 'order'], name='idx_column_project_order')],
            },
        ),
    ]
